-- Migração aditiva do monitoramento. Não remove nem atualiza dados editoriais.
CREATE TYPE "MonitorFrequency" AS ENUM ('DAILY','WEEKLY','MANUAL');
CREATE TYPE "MonitorRunStatus" AS ENUM ('RUNNING','COMPLETED','COMPLETED_WITH_WARNINGS','FAILED','SKIPPED','LOCKED');
CREATE TYPE "DocumentChangeType" AS ENUM ('NEW_DOCUMENT','CONTENT_CHANGED','DOCUMENT_REMOVED_FROM_PAGE','DOCUMENT_RENAMED','CLASSIFICATION_CHANGED','UNCHANGED');
CREATE TYPE "DocumentImpactType" AS ENUM ('NEW_EXAM','NEW_ANSWER_KEY_PRELIMINARY','NEW_ANSWER_KEY_FINAL','ANSWER_KEY_CHANGED','RECTIFICATION','ANNULMENT_NOTICE','NOTICE_CHANGED','NEW_RESULT','UNKNOWN','NO_EDITORIAL_IMPACT');
CREATE TYPE "ChangeReviewStatus" AS ENUM ('WAITING_REVIEW','ACKNOWLEDGED','IMPORT_JOB_CREATED','DISMISSED','RESOLVED');
CREATE TYPE "EditorialProposalStatus" AS ENUM ('PENDING','ACCEPTED','REJECTED','APPLIED','CONFLICT');

ALTER TABLE "ImportJob" ADD COLUMN "documentChangeId" TEXT, ADD COLUMN "isUpdate" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "sourceMonitorId" TEXT;
CREATE TABLE "SourceMonitor" ("id" TEXT NOT NULL PRIMARY KEY,"name" TEXT NOT NULL,"sourceUrl" TEXT NOT NULL,"adapterType" TEXT NOT NULL,"institution" TEXT NOT NULL,"boardId" TEXT,"editorialCatalogEntryId" TEXT,"contestId" TEXT,"enabled" BOOLEAN NOT NULL DEFAULT true,"frequency" "MonitorFrequency" NOT NULL,"notes" TEXT,"lastCheckedAt" TIMESTAMP(3),"nextCheckAt" TIMESTAMP(3),"lastSuccessfulAt" TIMESTAMP(3),"lastErrorAt" TIMESTAMP(3),"lastError" TEXT,"consecutiveFailures" INTEGER NOT NULL DEFAULT 0,"lockedAt" TIMESTAMP(3),"lockedBy" TEXT,"lockExpiresAt" TIMESTAMP(3),"lastManualRunAt" TIMESTAMP(3),"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "MonitorRun" ("id" TEXT NOT NULL PRIMARY KEY,"sourceMonitorId" TEXT NOT NULL,"status" "MonitorRunStatus" NOT NULL,"lockToken" TEXT,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"finishedAt" TIMESTAMP(3),"documentsDiscovered" INTEGER NOT NULL DEFAULT 0,"documentsNew" INTEGER NOT NULL DEFAULT 0,"documentsChanged" INTEGER NOT NULL DEFAULT 0,"documentsUnchanged" INTEGER NOT NULL DEFAULT 0,"warnings" JSONB,"error" TEXT,"attempts" INTEGER NOT NULL DEFAULT 1,"dryRun" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "DocumentChange" ("id" TEXT NOT NULL PRIMARY KEY,"monitorRunId" TEXT NOT NULL,"sourceDocumentId" TEXT,"previousDocumentId" TEXT,"changeType" "DocumentChangeType" NOT NULL,"impactType" "DocumentImpactType" NOT NULL,"status" "ChangeReviewStatus" NOT NULL DEFAULT 'WAITING_REVIEW',"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "EditorialChangeProposal" ("id" TEXT NOT NULL PRIMARY KEY,"documentChangeId" TEXT NOT NULL,"contestId" TEXT NOT NULL,"questionId" TEXT,"field" TEXT NOT NULL,"previousValue" JSONB,"proposedValue" JSONB,"sourceDocumentId" TEXT NOT NULL,"sourcePage" INTEGER,"status" "EditorialProposalStatus" NOT NULL DEFAULT 'PENDING',"reviewedById" TEXT,"reviewedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AdminNotification" ("id" TEXT NOT NULL PRIMARY KEY,"documentChangeId" TEXT NOT NULL,"title" TEXT NOT NULL,"severity" TEXT NOT NULL,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "SourceMonitor_enabled_nextCheckAt_idx" ON "SourceMonitor"("enabled","nextCheckAt");
CREATE INDEX "SourceMonitor_contestId_idx" ON "SourceMonitor"("contestId");
CREATE INDEX "SourceMonitor_editorialCatalogEntryId_idx" ON "SourceMonitor"("editorialCatalogEntryId");
CREATE INDEX "SourceMonitor_boardId_idx" ON "SourceMonitor"("boardId");
CREATE INDEX "MonitorRun_sourceMonitorId_startedAt_idx" ON "MonitorRun"("sourceMonitorId","startedAt");
CREATE INDEX "MonitorRun_status_idx" ON "MonitorRun"("status");
CREATE INDEX "DocumentChange_monitorRunId_idx" ON "DocumentChange"("monitorRunId");
CREATE INDEX "DocumentChange_status_impactType_idx" ON "DocumentChange"("status","impactType");
CREATE INDEX "DocumentChange_sourceDocumentId_idx" ON "DocumentChange"("sourceDocumentId");
CREATE INDEX "EditorialChangeProposal_documentChangeId_idx" ON "EditorialChangeProposal"("documentChangeId");
CREATE INDEX "EditorialChangeProposal_contestId_status_idx" ON "EditorialChangeProposal"("contestId","status");
CREATE INDEX "EditorialChangeProposal_questionId_idx" ON "EditorialChangeProposal"("questionId");
CREATE UNIQUE INDEX "AdminNotification_documentChangeId_key" ON "AdminNotification"("documentChangeId");
CREATE INDEX "AdminNotification_readAt_severity_idx" ON "AdminNotification"("readAt","severity");
CREATE INDEX "ImportJob_sourceMonitorId_idx" ON "ImportJob"("sourceMonitorId");
CREATE INDEX "ImportJob_documentChangeId_idx" ON "ImportJob"("documentChangeId");
ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_sourceMonitorId_fkey" FOREIGN KEY ("sourceMonitorId") REFERENCES "SourceMonitor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_documentChangeId_fkey" FOREIGN KEY ("documentChangeId") REFERENCES "DocumentChange"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SourceMonitor" ADD CONSTRAINT "SourceMonitor_boardId_fkey" FOREIGN KEY ("boardId") REFERENCES "Banca"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SourceMonitor" ADD CONSTRAINT "SourceMonitor_editorialCatalogEntryId_fkey" FOREIGN KEY ("editorialCatalogEntryId") REFERENCES "EditorialCatalogEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SourceMonitor" ADD CONSTRAINT "SourceMonitor_contestId_fkey" FOREIGN KEY ("contestId") REFERENCES "Concurso"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SourceMonitor" ADD CONSTRAINT "SourceMonitor_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MonitorRun" ADD CONSTRAINT "MonitorRun_sourceMonitorId_fkey" FOREIGN KEY ("sourceMonitorId") REFERENCES "SourceMonitor"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentChange" ADD CONSTRAINT "DocumentChange_monitorRunId_fkey" FOREIGN KEY ("monitorRunId") REFERENCES "MonitorRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentChange" ADD CONSTRAINT "DocumentChange_sourceDocumentId_fkey" FOREIGN KEY ("sourceDocumentId") REFERENCES "SourceDocument"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DocumentChange" ADD CONSTRAINT "DocumentChange_previousDocumentId_fkey" FOREIGN KEY ("previousDocumentId") REFERENCES "SourceDocument"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "EditorialChangeProposal" ADD CONSTRAINT "EditorialChangeProposal_documentChangeId_fkey" FOREIGN KEY ("documentChangeId") REFERENCES "DocumentChange"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EditorialChangeProposal" ADD CONSTRAINT "EditorialChangeProposal_contestId_fkey" FOREIGN KEY ("contestId") REFERENCES "Concurso"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EditorialChangeProposal" ADD CONSTRAINT "EditorialChangeProposal_sourceDocumentId_fkey" FOREIGN KEY ("sourceDocumentId") REFERENCES "SourceDocument"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EditorialChangeProposal" ADD CONSTRAINT "EditorialChangeProposal_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdminNotification" ADD CONSTRAINT "AdminNotification_documentChangeId_fkey" FOREIGN KEY ("documentChangeId") REFERENCES "DocumentChange"("id") ON DELETE CASCADE ON UPDATE CASCADE;
