import Link from "next/link";
import { AdminShell } from "@/components/layout/AdminShell";
import { requireAdmin } from "@/lib/admin";
import { prisma } from "@/lib/prisma";
import { reviewChangeAction, reviewProposalAction } from "../actions";

export default async function ChangesPage({searchParams}:{searchParams:Promise<{status?:string;impact?:string}>}) {
  await requireAdmin(); const query=await searchParams;
  const changes=await prisma.documentChange.findMany({where:{...(query.status?{status:query.status as any}:{}),...(query.impact?{impactType:query.impact as any}:{})},include:{monitorRun:{include:{sourceMonitor:{include:{board:true}}}},sourceDocument:true,previousDocument:true,importJobs:true,proposals:true,notification:true},orderBy:{createdAt:"desc"},take:200});
  return <AdminShell><main className="mx-auto max-w-7xl px-4 py-10"><Link href="/admin/monitoramento" className="font-bold text-emerald-800">← Monitoramento</Link><h1 className="mt-4 text-3xl font-black text-emerald-950">Atualizações oficiais pendentes</h1>
  <form className="mt-5 flex gap-3"><select name="status" defaultValue={query.status??""} className="input"><option value="">Todos os status</option><option>WAITING_REVIEW</option><option>ACKNOWLEDGED</option><option>DISMISSED</option><option>RESOLVED</option></select><input name="impact" defaultValue={query.impact??""} placeholder="Impacto" className="input"/><button className="rounded-xl bg-amber-400 px-4 font-black">Filtrar</button></form>
  <div className="mt-6 space-y-4">{changes.map(change=><article key={change.id} className="rounded-2xl border border-stone-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black uppercase text-amber-700">{change.impactType} · {change.changeType}</p><h2 className="mt-1 text-xl font-black text-emerald-950">{change.monitorRun.sourceMonitor.name}</h2><p className="text-sm">{change.notification?.title}</p></div><span>{change.status}</span></div>
  <div className="mt-3 grid gap-2 text-xs md:grid-cols-2"><p>Anterior: <code>{change.previousDocument?.sha256??"—"}</code></p><p>Novo: <code>{change.sourceDocument?.sha256??"—"}</code></p></div>
  <div className="mt-3 flex gap-3">{change.sourceDocument&&<a target="_blank" href={`/api/admin/importacoes/${change.sourceDocument.importJobId}/documentos/${change.sourceDocument.id}`} className="font-bold text-emerald-800">Abrir documento novo</a>}{change.previousDocument&&<a target="_blank" href={`/api/admin/importacoes/${change.previousDocument.importJobId}/documentos/${change.previousDocument.id}`} className="font-bold text-emerald-800">Abrir anterior</a>}{change.importJobs[0]&&<Link href={`/admin/importacoes/${change.importJobs[0].id}`} className="font-bold text-emerald-800">Abrir ImportJob</Link>}</div>
  {change.proposals.map(proposal=><div key={proposal.id} className="mt-3 rounded-xl bg-amber-50 p-3 text-sm"><b>Proposta: {proposal.field}</b><p>{JSON.stringify(proposal.previousValue)} → {JSON.stringify(proposal.proposedValue)}</p><p>Status: {proposal.status}</p>{proposal.status==="PENDING"&&<div className="mt-2 flex gap-2"><form action={reviewProposalAction}><input type="hidden" name="proposalId" value={proposal.id}/><input type="hidden" name="status" value="ACCEPTED"/><button className="font-bold text-emerald-800">Aceitar proposta (não aplicar)</button></form><form action={reviewProposalAction}><input type="hidden" name="proposalId" value={proposal.id}/><input type="hidden" name="status" value="REJECTED"/><button className="font-bold text-red-700">Rejeitar</button></form></div>}</div>)}
  {change.status==="WAITING_REVIEW"&&<form action={reviewChangeAction} className="mt-4 flex flex-wrap gap-2"><input type="hidden" name="changeId" value={change.id}/><input name="justification" placeholder="Justificativa para descarte" className="input"/><button name="reviewAction" value="ACKNOWLEDGED" className="rounded-lg bg-emerald-900 px-3 py-2 font-bold text-white">Reconhecer</button><button name="reviewAction" value="DISMISSED" className="rounded-lg border border-red-300 px-3 py-2 font-bold text-red-700">Descartar</button></form>}
  </article>)}</div></main></AdminShell>;
}
